= Usage

== Configure Role
Configure a role that maps a name in Vault to a set of creation statements to create the horizon credentials:
[source, shell]
----
$ vault write horizon/roles/<role-name> \
	instance=<instance> \
	roles=... \
	contact=... \
	ttl=1h \
	max_ttl=24h
----

|======
| Parameter | Description

| instance | The horizon instance defined in the horizon/config (mandatory)
| roles | Roles predefined in horizon, which you want to assign to the new credential
| contact | Email address (mandatory)
| ttl | Life duration for the credential
| max_ttl | Maximale life duration for the credential
| password_policy | The password policy used to generate the password
| username_policy | The username policy used to generate the username
|======

The {{username}} and {{password}} fields will be populated by the plugin with dynamically generated values.

== Credential Generation
After the secrets engine is configured and a user/machine has a Vault token with the proper permission, it can generate credentials.

Generate a new credential by reading from the `/creds` endpoint with the name of the role:
[source, shell]
----
$ vault read horizon/creds/<role-name>
----